package main

// Part 1: Implement MapReduce from start to finish for a simple word count program
// You only need to modify the Map, Reduce, and MapReduce functions.

import (
	"container/list"
	"fmt"
	"os"
)


type KeyValue struct {
	Key   string
	Value string
}

// Our simplified version of MapReduce does not supply a
// key to the Map function; only a string value, which is
// the input file content. the return value should be a list
// of key/value pairs, each represented by a KeyValue object.
// 
// Duplicate keys are expected in the returned result.
// Do not prematurely combine them here (even though you can) - do that in the DoMapReduce function.
func Map(value string) *list.List {
	// Your code here
	return nil
}

// Called once for each key generated by Map, with a list
// of that key's string value. should return a single string
// output value for that key.
// Technically, a reducer should be able to return an arbitrary number of results,
// but for simplicity, we assume each reducer only outputs one combined value per key
func Reduce(key string, values *list.List) string {
	// Your code here
	return ""
}

// Use your Map and Reduce functions to do a MapReduce job on the input string
// For now, do not worry about task division - Map should be called once,
// and Reduce called once for every unique key output by Map
// Speed is not a concern for this function - correctness is more important,
// as we will be implementing distributed MapReduce later!
func DoMapReduce(input string) []string {
	// Your code here
	return nil
}


// Use this to test your code. Do not modify the code below.
// Run like so: go run wc.go input.txt
func main() {
	if len(os.Args) != 2 {
		fmt.Printf("wc.go: usage is go run wc.go <input_file>\n")
		return
	}
	filename := string(os.Args[1]) 
	contentBytes, err := os.ReadFile(filename)
	if err != nil {
		fmt.Printf("Error reading file: %v\n", err)
		return
	}

	// Convert bytes to string and pass to DoMapReduce
	output := DoMapReduce(string(contentBytes))

	// Print the result
	for _, value := range output {
		fmt.Printf("%v\n", value)
	}
}
